env: local # local dev prod
http_server:
  host: 0.0.0.0
  port: 8000
grpc_server:
  host: 0.0.0.0
  port: 3000
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db_name: postgres
jwt:
  expires: 60
  secret: your-secret
redis:
  host: localhost
  port: 6379
  password:
notification-service:
  address: localhost:3000