name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Build the Docker image
        run: docker build -t auth-service:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image to Docker Hub
        run: docker tag auth-service:latest ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
            docker stop auth-service || true
            docker rm auth-service || true
            echo "${{ secrets.PROD_CONFIG }} > /config/prod.yaml"
            docker run -d \
              --name auth-service \ 
              -e CONFIG_PATH=/config/prod.yaml \
              -v ~/serviceDesk/auth-service/config:/config \
              -p 8001:8000 -p 3001:3000 \
              --restart unless-stop \
              --network sirius-service-desk \
              ${{ secrets.DOCKER_USERNAME }}/auth-service:latest
